version: '3'

networks:
  app_network:
    driver: bridge


services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app1/api/storage:/usr/share/nginx/storage
      - ./app1/ui/dist:/usr/share/nginx/html
    restart: always
    networks:
      - app_network

  api:
    container_name: api
    hostname: api
    build:
      context: ./app1/api
      args:
        - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmjs.org/}
        - BUILD_ENV=${BUILD_ENV:-production}
        - ${API_PORT:-3000}:${API_PORT:-3000}
    env_file:
      - ${ENV_FILE:-./.env}
    environment:
      - BUILD_ENV=${BUILD_ENV:-production}
    expose:
      - ${API_PORT:-3000}
    restart: always
    volumes:
      - ./app1/api/config:/opt/app/config
      - ./app1/api/src:/opt/app/src
      - ./app1/api/storage:/opt/app/storage
    networks:
      - app_network
    depends_on:
      - nginx

  ui:
    container_name: ui
    build:
      context: ./app1/ui
      args:
        - NPM_REGISTRY=${NPM_REGISTRY:-https://registry.npmjs.org/}
    volumes:
      - ./app1/ui/dist:/app/dist
    networks:
      - app_network
    depends_on:
      - nginx
